# Generated by Django 3.0.7 on 2020-07-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_company_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='arrival',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='departure',
            new_name='departure_time',
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default=0, max_length=9999, verbose_name="Company's description"),
        ),
    ]
