# Generated by Django 3.0.7 on 2020-07-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200712_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Seat price'),
        ),
    ]
